basepath = "."

locales = [
  "cs",
  "de",
  "fr",
  "it",
  "pl",
  "ru",
  "sl",
]

[env]
  l = "{l10n_base}/values-{android_locale}"

[[paths]]
  reference = "values/strings.xml"
  l10n = "{l}strings.xml"
