basepath = "."
locales = ["cs", "de", "fr", "it", "pl", "ru", "sl", "af", "ak", "hy-AM"]

[env]
l = "{l10n_base}/values-{android_locale}/"

[[paths]]
l10n = "{l}strings.xml"
reference = "values/strings.xml"
